server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
  max-http-request-header-size: 16KB
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10
  servlet:
    context-path: /api/v1

spring:
  application:
    name: template-api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  mvc:
    problemdetails:
      enabled: false

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: false
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    root: INFO
    com.benseddik.template: INFO
    com.benseddik.template.security: INFO
    com.benseddik.template.error: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/template.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT_ID}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  admin:
    username: ${KEYCLOAK_ADMIN_USER}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}
  security:
    jwt:
      clock-skew-seconds: 60

rustfs:
  endpoint: ${RUSTFS_ENDPOINT}
  access-key: ${RUSTFS_ACCESS_KEY}
  secret-key: ${RUSTFS_SECRET_KEY}
  bucket-name: ${RUSTFS_BUCKET_NAME}
  region: ${RUSTFS_REGION}
