server:
  port: 0
  error:
    include-message: always
    include-stacktrace: on-param
  servlet:
    context-path: /api/v1

spring:
  application:
    name: template-api-test
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  mvc:
    problemdetails:
      enabled: false

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

  # H2 Database for testing
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 10000

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  # Disable Liquibase for tests (using ddl-auto: create-drop)
  liquibase:
    enabled: false

  # Mock OAuth2 configuration for tests
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/test-realm
          jwk-set-uri: http://localhost:8081/realms/test-realm/protocol/openid-connect/certs

  lifecycle:
    timeout-per-shutdown-phase: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    root: INFO
    com.benseddik.template: DEBUG
    com.benseddik.template.security: DEBUG
    com.benseddik.template.error: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Test configuration - not used in actual tests (mocked)
keycloak:
  auth-server-url: http://localhost:8081
  realm: test-realm
  resource: test-client
  credentials:
    secret: test-secret
  admin:
    username: admin
    password: admin

app:
  cors:
    allowed-origins: http://localhost:3000
  security:
    jwt:
      clock-skew-seconds: 300

# Test configuration - not used in actual tests (mocked)
rustfs:
  endpoint: http://localhost:9000
  access-key: test-access-key
  secret-key: test-secret-key
  bucket-name: test-bucket
  region: us-east-1
